name: Run autorun script on push
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip

    - name: Run autorun script
      run: |
        chmod +x ./autorun.sh
        ./autorun.sh
